name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2 
        with:
          bun-version: latest

      - name: Setup Java for Android
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Android SDK components
        run: |
          brew install --cask android-commandlinetools
          yes | sdkmanager "platforms;android-33" "build-tools;33.0.0" "ndk;21.4.7075529"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.gradle/caches
            ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json', '**/build.gradle', '**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        run: bun install

      - name: Update version if provided
        if: github.event_name == 'workflow_dispatch' && inputs.version != ''
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Update version in package.json
          jq '.version = "${{ github.event.inputs.version }}"' package.json > package.json.tmp
          mv package.json.tmp package.json
          
          # Commit and push the changes
          git add package.json
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git tag "v${{ github.event.inputs.version }}"
          git push origin main
          git push origin "v${{ github.event.inputs.version }}"

      - name: Verify all platforms
        run: bun run verify
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk

      - name: Build package
        run: bun run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch' && inputs.version != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          name: "v${{ github.event.inputs.version }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} 